### ISSUE TITLE
Eric's cursor

### ISSUE THREAD

**Issue by milofultz** [Idakka/Project-Atelier#110]
When Eric clicks on an HTML element, it shows a cursor, regardless if it is contenteditable, input element, or not. I think this is related to a setting that is in chrome, as seen here:

https://support.google.com/chrome/thread/77878717/there-is-a-text-cursor-bug-in-my-chrome-that-causes-the-blinking-cursor-to-appear-everywhere-i-click?hl=en

**Comment by NylonEric** [comment]
Change made.
